# version: "3.9"
# services:
#   app:
#     build: .
#     ports:
#       - 8000:8080
#     # volumes:
#     #   - .:/app

version: "3.9"
services:
  app:
    container_name: webservice-v2_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - TEST_POSTGRES_USER=${TEST_DB_USER}
      - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_DB_NAME}
      - TEST_DATABASE_HOST=${TEST_DB_HOST}
      - TEST_DATABASE_PORT=${TEST_DB_PORT}
    tty: true
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "1234:5432"

  postgresdb_test:
    image: postgres:latest
    container_name: postgres_test_container
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST}
    ports:
      - "4568:5432"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data

  # migrate:
  #   image: migrate/migrate
  #   container_name: migrate_container
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - DATABASE_HOST=${DB_HOST}
  #     - DATABASE_PORT=${DB_PORT}
  #   volumes:
  #     - ./repository/database/migrations:/migrations
  #   command: [
  #       "-path",
  #       # "app/repository/database/migrations",
  #       "migrations",
  #       "-database",
  #       "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
  #       #"postgres://webservice_dev_user:yourpassword@db:5432/webservice_dev?sslmode=disable",
  #       "up",
  #       # "3",
  #     ]
  #   depends_on:
  #     - db

volumes:
  postgres-data:
  postgres-data-test:
